#!/usr/bin/env python3
"""Generate src/app_language_catalog.rs from backend/i18n/languages.json.

languages.json is the single source of truth for the 41-language catalogue and
its alias table. The backend generates backend/common/src/i18n/data.rs and
riseonly-ios/.../AppLanguageCatalog.swift from it with
backend/scripts/gen_i18n_data.py; this is the same job for the desktop tree.

    python3 crates/rise-i18n/tools/gen_catalog.py [languages.json] [--check]

--check exits non-zero if the generated file is stale instead of rewriting it.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve()
CRATE = HERE.parents[1]
WORKSPACE = HERE.parents[4]
DEFAULT_SOURCE = WORKSPACE / "backend" / "i18n" / "languages.json"
OUTPUT = CRATE / "src" / "app_language_catalog.rs"

# languages.json names CLDR families in snake_case; the Rust variants are the
# same names in UpperCamelCase, matching backend/common/src/i18n/plural.rs.
VARIANTS = {
    "arabic": "Arabic",
    "czech": "Czech",
    "filipino": "Filipino",
    "hebrew": "Hebrew",
    "one_other": "OneOther",
    "one_zero_other": "OneZeroOther",
    "other_only": "OtherOnly",
    "polish": "Polish",
    "romanian": "Romanian",
    "serbian": "Serbian",
    "slavic": "Slavic",
}

HEADER = """// @generated by crates/rise-i18n/tools/gen_catalog.py \
from backend/i18n/languages.json
// Do not edit by hand — edit languages.json and regenerate.
"""


def rust_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(doc: dict) -> str:
    languages = doc["languages"]
    aliases = doc["aliases"]
    families = sorted({lang["plural"] for lang in languages})
    unknown = [f for f in families if f not in VARIANTS]
    if unknown:
        raise SystemExit(f"unknown plural family in languages.json: {unknown}")

    out: list[str] = [HEADER]

    out.append("/// CLDR cardinal rule families, one per distinct ruleset the")
    out.append("/// catalogue needs. Selection lives in `app_plural_selector`.")
    out.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
    out.append("pub enum PluralRules {")
    for family in families:
        out.append(f"    {VARIANTS[family]},")
    out.append("}\n")

    out.append("impl PluralRules {")
    out.append("    pub const fn as_str(self) -> &'static str {")
    out.append("        match self {")
    for family in families:
        out.append(f"            Self::{VARIANTS[family]} => {rust_str(family)},")
    out.append("        }")
    out.append("    }\n")
    out.append("    pub fn from_name(raw: &str) -> Option<Self> {")
    out.append("        match raw {")
    for family in families:
        out.append(f"            {rust_str(family)} => Some(Self::{VARIANTS[family]}),")
    out.append("            _ => None,")
    out.append("        }")
    out.append("    }")
    out.append("}\n")

    out.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
    out.append("pub struct AppLanguage {")
    out.append("    pub code: &'static str,")
    out.append("    pub native_name: &'static str,")
    out.append("    pub english_name: &'static str,")
    out.append("    pub is_rtl: bool,")
    out.append("    pub locale_identifier: &'static str,")
    out.append("    pub plural: PluralRules,")
    out.append("}\n")

    out.append(f"pub const REVISION: u32 = {int(doc['revision'])};")
    out.append(f"pub const BASE_LANGUAGE: &str = {rust_str(doc['base_language'])};\n")

    out.append("pub static ALL: &[AppLanguage] = &[")
    for lang in languages:
        out.append("    AppLanguage {")
        out.append(f"        code: {rust_str(lang['code'])},")
        out.append(f"        native_name: {rust_str(lang['native'])},")
        out.append(f"        english_name: {rust_str(lang['english'])},")
        out.append(f"        is_rtl: {'true' if lang['rtl'] else 'false'},")
        out.append(f"        locale_identifier: {rust_str(lang['locale'])},")
        out.append(f"        plural: PluralRules::{VARIANTS[lang['plural']]},")
        out.append("    },")
    out.append("];\n")

    out.append("pub static ALIASES: &[(&str, &str)] = &[")
    for key in sorted(aliases):
        out.append(f"    ({rust_str(key)}, {rust_str(aliases[key])}),")
    out.append("];\n")

    out.append("pub fn language(code: &str) -> Option<&'static AppLanguage> {")
    out.append("    ALL.iter().find(|entry| entry.code == code)")
    out.append("}\n")

    out.append("pub fn alias_target(tag: &str) -> Option<&'static str> {")
    out.append("    ALIASES")
    out.append("        .iter()")
    out.append("        .find(|(alias, _)| alias.eq_ignore_ascii_case(tag))")
    out.append("        .map(|(_, target)| *target)")
    out.append("}\n")

    out.append("pub fn codes() -> impl Iterator<Item = &'static str> {")
    out.append("    ALL.iter().map(|entry| entry.code)")
    out.append("}")

    return "\n".join(out) + "\n"


def main() -> int:
    args = [a for a in sys.argv[1:] if a != "--check"]
    check = "--check" in sys.argv[1:]
    source = Path(args[0]) if args else DEFAULT_SOURCE
    if not source.is_file():
        raise SystemExit(f"languages.json not found: {source}")

    generated = render(json.loads(source.read_text(encoding="utf-8")))

    if check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != generated:
            print(f"stale: {OUTPUT} does not match {source}")
            return 1
        print("app_language_catalog.rs: up to date")
        return 0

    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
