// @generated by crates/rise-i18n/tools/gen_catalog.py from backend/i18n/languages.json
// Do not edit by hand — edit languages.json and regenerate.

/// CLDR cardinal rule families, one per distinct ruleset the
/// catalogue needs. Selection lives in `app_plural_selector`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PluralRules {
    Arabic,
    Czech,
    Filipino,
    Hebrew,
    OneOther,
    OneZeroOther,
    OtherOnly,
    Polish,
    Romanian,
    Serbian,
    Slavic,
}

impl PluralRules {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Arabic => "arabic",
            Self::Czech => "czech",
            Self::Filipino => "filipino",
            Self::Hebrew => "hebrew",
            Self::OneOther => "one_other",
            Self::OneZeroOther => "one_zero_other",
            Self::OtherOnly => "other_only",
            Self::Polish => "polish",
            Self::Romanian => "romanian",
            Self::Serbian => "serbian",
            Self::Slavic => "slavic",
        }
    }

    pub fn from_name(raw: &str) -> Option<Self> {
        match raw {
            "arabic" => Some(Self::Arabic),
            "czech" => Some(Self::Czech),
            "filipino" => Some(Self::Filipino),
            "hebrew" => Some(Self::Hebrew),
            "one_other" => Some(Self::OneOther),
            "one_zero_other" => Some(Self::OneZeroOther),
            "other_only" => Some(Self::OtherOnly),
            "polish" => Some(Self::Polish),
            "romanian" => Some(Self::Romanian),
            "serbian" => Some(Self::Serbian),
            "slavic" => Some(Self::Slavic),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct AppLanguage {
    pub code: &'static str,
    pub native_name: &'static str,
    pub english_name: &'static str,
    pub is_rtl: bool,
    pub locale_identifier: &'static str,
    pub plural: PluralRules,
}

pub const REVISION: u32 = 1;
pub const BASE_LANGUAGE: &str = "en";

pub static ALL: &[AppLanguage] = &[
    AppLanguage {
        code: "ar",
        native_name: "العربية",
        english_name: "Arabic",
        is_rtl: true,
        locale_identifier: "ar_SA",
        plural: PluralRules::Arabic,
    },
    AppLanguage {
        code: "bn",
        native_name: "বাংলা",
        english_name: "Bengali",
        is_rtl: false,
        locale_identifier: "bn_BD",
        plural: PluralRules::OneZeroOther,
    },
    AppLanguage {
        code: "cs",
        native_name: "Čeština",
        english_name: "Czech",
        is_rtl: false,
        locale_identifier: "cs_CZ",
        plural: PluralRules::Czech,
    },
    AppLanguage {
        code: "da",
        native_name: "Dansk",
        english_name: "Danish",
        is_rtl: false,
        locale_identifier: "da_DK",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "de",
        native_name: "Deutsch",
        english_name: "German",
        is_rtl: false,
        locale_identifier: "de_DE",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "el",
        native_name: "Ελληνικά",
        english_name: "Greek",
        is_rtl: false,
        locale_identifier: "el_GR",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "en",
        native_name: "English",
        english_name: "English",
        is_rtl: false,
        locale_identifier: "en_US",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "es",
        native_name: "Español",
        english_name: "Spanish",
        is_rtl: false,
        locale_identifier: "es_ES",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "fa",
        native_name: "فارسی",
        english_name: "Persian",
        is_rtl: true,
        locale_identifier: "fa_IR",
        plural: PluralRules::OneZeroOther,
    },
    AppLanguage {
        code: "fi",
        native_name: "Suomi",
        english_name: "Finnish",
        is_rtl: false,
        locale_identifier: "fi_FI",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "fr",
        native_name: "Français",
        english_name: "French",
        is_rtl: false,
        locale_identifier: "fr_FR",
        plural: PluralRules::OneZeroOther,
    },
    AppLanguage {
        code: "he",
        native_name: "עברית",
        english_name: "Hebrew",
        is_rtl: true,
        locale_identifier: "he_IL",
        plural: PluralRules::Hebrew,
    },
    AppLanguage {
        code: "hi",
        native_name: "हिन्दी",
        english_name: "Hindi",
        is_rtl: false,
        locale_identifier: "hi_IN",
        plural: PluralRules::OneZeroOther,
    },
    AppLanguage {
        code: "hu",
        native_name: "Magyar",
        english_name: "Hungarian",
        is_rtl: false,
        locale_identifier: "hu_HU",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "id",
        native_name: "Bahasa Indonesia",
        english_name: "Indonesian",
        is_rtl: false,
        locale_identifier: "id_ID",
        plural: PluralRules::OtherOnly,
    },
    AppLanguage {
        code: "it",
        native_name: "Italiano",
        english_name: "Italian",
        is_rtl: false,
        locale_identifier: "it_IT",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "ja",
        native_name: "日本語",
        english_name: "Japanese",
        is_rtl: false,
        locale_identifier: "ja_JP",
        plural: PluralRules::OtherOnly,
    },
    AppLanguage {
        code: "ka",
        native_name: "ქართული",
        english_name: "Georgian",
        is_rtl: false,
        locale_identifier: "ka_GE",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "kk",
        native_name: "Қазақша",
        english_name: "Kazakh",
        is_rtl: false,
        locale_identifier: "kk_KZ",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "ko",
        native_name: "한국어",
        english_name: "Korean",
        is_rtl: false,
        locale_identifier: "ko_KR",
        plural: PluralRules::OtherOnly,
    },
    AppLanguage {
        code: "ms",
        native_name: "Bahasa Melayu",
        english_name: "Malay",
        is_rtl: false,
        locale_identifier: "ms_MY",
        plural: PluralRules::OtherOnly,
    },
    AppLanguage {
        code: "nl",
        native_name: "Nederlands",
        english_name: "Dutch",
        is_rtl: false,
        locale_identifier: "nl_NL",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "no",
        native_name: "Norsk",
        english_name: "Norwegian",
        is_rtl: false,
        locale_identifier: "nb_NO",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "pl",
        native_name: "Polski",
        english_name: "Polish",
        is_rtl: false,
        locale_identifier: "pl_PL",
        plural: PluralRules::Polish,
    },
    AppLanguage {
        code: "pt",
        native_name: "Português",
        english_name: "Portuguese",
        is_rtl: false,
        locale_identifier: "pt_PT",
        plural: PluralRules::OneZeroOther,
    },
    AppLanguage {
        code: "pt-BR",
        native_name: "Português (Brasil)",
        english_name: "Portuguese (Brazil)",
        is_rtl: false,
        locale_identifier: "pt_BR",
        plural: PluralRules::OneZeroOther,
    },
    AppLanguage {
        code: "ro",
        native_name: "Română",
        english_name: "Romanian",
        is_rtl: false,
        locale_identifier: "ro_RO",
        plural: PluralRules::Romanian,
    },
    AppLanguage {
        code: "ru",
        native_name: "Русский",
        english_name: "Russian",
        is_rtl: false,
        locale_identifier: "ru_RU",
        plural: PluralRules::Slavic,
    },
    AppLanguage {
        code: "sr",
        native_name: "Српски",
        english_name: "Serbian",
        is_rtl: false,
        locale_identifier: "sr_RS",
        plural: PluralRules::Serbian,
    },
    AppLanguage {
        code: "sv",
        native_name: "Svenska",
        english_name: "Swedish",
        is_rtl: false,
        locale_identifier: "sv_SE",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "sw",
        native_name: "Kiswahili",
        english_name: "Swahili",
        is_rtl: false,
        locale_identifier: "sw_KE",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "ta",
        native_name: "தமிழ்",
        english_name: "Tamil",
        is_rtl: false,
        locale_identifier: "ta_IN",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "th",
        native_name: "ไทย",
        english_name: "Thai",
        is_rtl: false,
        locale_identifier: "th_TH",
        plural: PluralRules::OtherOnly,
    },
    AppLanguage {
        code: "tl",
        native_name: "Filipino",
        english_name: "Filipino",
        is_rtl: false,
        locale_identifier: "fil_PH",
        plural: PluralRules::Filipino,
    },
    AppLanguage {
        code: "tr",
        native_name: "Türkçe",
        english_name: "Turkish",
        is_rtl: false,
        locale_identifier: "tr_TR",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "uk",
        native_name: "Українська",
        english_name: "Ukrainian",
        is_rtl: false,
        locale_identifier: "uk_UA",
        plural: PluralRules::Slavic,
    },
    AppLanguage {
        code: "ur",
        native_name: "اردو",
        english_name: "Urdu",
        is_rtl: true,
        locale_identifier: "ur_PK",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "uz",
        native_name: "Oʻzbekcha",
        english_name: "Uzbek",
        is_rtl: false,
        locale_identifier: "uz_UZ",
        plural: PluralRules::OneOther,
    },
    AppLanguage {
        code: "vi",
        native_name: "Tiếng Việt",
        english_name: "Vietnamese",
        is_rtl: false,
        locale_identifier: "vi_VN",
        plural: PluralRules::OtherOnly,
    },
    AppLanguage {
        code: "zh-Hans",
        native_name: "简体中文",
        english_name: "Chinese (Simplified)",
        is_rtl: false,
        locale_identifier: "zh_Hans_CN",
        plural: PluralRules::OtherOnly,
    },
    AppLanguage {
        code: "zh-Hant",
        native_name: "繁體中文",
        english_name: "Chinese (Traditional)",
        is_rtl: false,
        locale_identifier: "zh_Hant_TW",
        plural: PluralRules::OtherOnly,
    },
];

pub static ALIASES: &[(&str, &str)] = &[
    ("bs", "sr"),
    ("en-AU", "en"),
    ("en-CA", "en"),
    ("en-GB", "en"),
    ("en-IN", "en"),
    ("es-419", "es"),
    ("es-AR", "es"),
    ("es-MX", "es"),
    ("fil", "tl"),
    ("hr", "sr"),
    ("in", "id"),
    ("iw", "he"),
    ("ji", "he"),
    ("mo", "ro"),
    ("nb", "no"),
    ("nn", "no"),
    ("pt-AO", "pt"),
    ("pt-MZ", "pt"),
    ("pt-PT", "pt"),
    ("sh", "sr"),
    ("sr-Latn", "sr"),
    ("zh", "zh-Hans"),
    ("zh-CN", "zh-Hans"),
    ("zh-HK", "zh-Hant"),
    ("zh-Hans-CN", "zh-Hans"),
    ("zh-Hant-TW", "zh-Hant"),
    ("zh-MO", "zh-Hant"),
    ("zh-SG", "zh-Hans"),
    ("zh-TW", "zh-Hant"),
];

pub fn language(code: &str) -> Option<&'static AppLanguage> {
    ALL.iter().find(|entry| entry.code == code)
}

pub fn alias_target(tag: &str) -> Option<&'static str> {
    ALIASES
        .iter()
        .find(|(alias, _)| alias.eq_ignore_ascii_case(tag))
        .map(|(_, target)| *target)
}

pub fn codes() -> impl Iterator<Item = &'static str> {
    ALL.iter().map(|entry| entry.code)
}
