//! Turns `assets/icons/sf-to-lucide.json` into a static table, so a missing icon
//! is a build failure rather than a blank square at runtime.

use std::collections::BTreeMap;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let map_path = manifest.join("../../assets/icons/sf-to-lucide.json");
    let icons_dir = manifest.join("../../assets/icons/lucide");

    println!("cargo:rerun-if-changed={}", map_path.display());
    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let source = std::fs::read_to_string(&map_path).unwrap_or_else(|error| {
        panic!(
            "cannot read {}: {error}\n\
             The SF Symbol to Lucide table is required — see assets/icons/CONTEXT.txt.",
            map_path.display()
        )
    });

    let document: Document = serde_json::from_str(&source).unwrap_or_else(|error| {
        panic!("{} is not the expected shape: {error}", map_path.display())
    });

    let mut missing = Vec::new();
    for lucide in document.map.values() {
        if !icons_dir.join(format!("{lucide}.svg")).is_file() {
            missing.push(lucide.clone());
        }
    }
    missing.sort();
    missing.dedup();
    if !missing.is_empty() {
        panic!(
            "{} names icons with no file in {}: {}",
            map_path.display(),
            icons_dir.display(),
            missing.join(", ")
        );
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out_dir.join("sf_to_lucide.rs"), render(&document)).unwrap();

    let flags_dir = manifest.join("../../assets/icons/flags");
    println!("cargo:rerun-if-changed={}", flags_dir.display());
    std::fs::write(out_dir.join("flags.rs"), render_flags(&flags_dir)).unwrap();
}

/// Listed at build time; probing the filesystem inside a frame is forbidden.
fn render_flags(dir: &PathBuf) -> String {
    let entries = std::fs::read_dir(dir).unwrap_or_else(|error| {
        panic!(
            "cannot list {}: {error}\n\
             The flag set is required — see assets/icons/flags/CONTEXT.txt.",
            dir.display()
        )
    });

    let mut codes: Vec<String> = entries
        .filter_map(|entry| entry.ok())
        .filter_map(|entry| {
            let name = entry.file_name().to_string_lossy().into_owned();
            let stem = name.strip_suffix(".svg")?;
            let is_region = stem.len() == 2 && stem.bytes().all(|b| b.is_ascii_lowercase());
            is_region.then(|| stem.to_owned())
        })
        .collect();
    codes.sort();
    codes.dedup();

    assert!(
        codes.len() > 200,
        "{} holds only {} region flags, which is not the shipped set",
        dir.display(),
        codes.len()
    );

    let mut out = String::new();
    out.push_str("// @generated by crates/rise-ui/build.rs from assets/icons/flags\n");
    out.push_str(&entries_table(
        "SHIPPED_FLAGS",
        "&str",
        codes.len(),
        codes.iter().map(|code| quote(code)),
    ));
    out
}

#[derive(serde::Deserialize)]
struct Document {
    /// Keyed by the SF Symbol name exactly as `riseonly-ios` writes it.
    map: BTreeMap<String, String>,
    /// SF names whose Lucide match is a compromise rather than an equivalent.
    #[serde(default)]
    approximate: Vec<String>,
}

fn render(document: &Document) -> String {
    let mut distinct: Vec<&String> = document.map.values().collect();
    distinct.sort();
    distinct.dedup();

    let mut approximate = document.approximate.clone();
    approximate.sort();

    let mut out = String::new();
    out.push_str("// @generated by crates/rise-ui/build.rs from assets/icons/sf-to-lucide.json\n");

    out.push_str(&entries_table(
        "SF_TO_LUCIDE",
        "(&str, &str)",
        document.map.len(),
        document
            .map
            .iter()
            .map(|(sf, lucide)| format!("({}, {})", quote(sf), quote(lucide))),
    ));

    out.push_str(&entries_table(
        "LUCIDE_ICONS",
        "&str",
        distinct.len(),
        distinct.iter().map(|name| quote(name)),
    ));

    out.push_str(&entries_table(
        "APPROXIMATE_SYMBOLS",
        "&str",
        approximate.len(),
        approximate.iter().map(|name| quote(name)),
    ));

    out
}

fn entries_table(
    name: &str,
    element: &str,
    len: usize,
    values: impl Iterator<Item = String>,
) -> String {
    let mut out = format!("pub static {name}: [{element}; {len}] = [\n");
    for value in values {
        out.push_str("    ");
        out.push_str(&value);
        out.push_str(",\n");
    }
    out.push_str("];\n\n");
    out
}

/// Escaping is defensive: a hand-edited table must not emit uncompilable code.
fn quote(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}
